### ISSUE TITLE
vendor.js: Unhandled Promise rejection: []: Cannot read properties of undefined (reading 'newrelic')

### ISSUE THREAD

**Issue by hughknaus** [newrelic/newrelic-capacitor-plugin#72]
## Description
I'm getting the below error in the console.log when starting the application:
```
index.js:40 []: Unhandled Promise rejection: []: Cannot read properties of undefined (reading 'newrelic') []: ; Zone: []: <root> []: ; Task: []: Promise.then []: ; Value: []: TypeError: Cannot read properties of undefined (reading 'newrelic') []: TypeError: Cannot read properties of undefined (reading 'newrelic')
    at http://localhost:8100/vendor.js:13197:46
    at _ZoneDelegate.invoke (http://localhost:8100/polyfills.js:8293:158)
    at Zone.run (http://localhost:8100/polyfills.js:8078:35)
    at http://localhost:8100/polyfills.js:9154:28
    at _ZoneDelegate.invokeTask (http://localhost:8100/polyfills.js:8320:171)
    at Zone.runTask (http://localhost:8100/polyfills.js:8124:37)
    at drainMicroTaskQueue (http://localhost:8100/polyfills.js:8491:23)
```

Also, seeing empty array brackets `[]` before each console logging output like:
```
[]: DEBUG::HomePageService::locateHomePage
[]: AppMenu ctor called
[]: AppMenuFooter Ctor called!
```

## Steps to Reproduce
- Npm installed @newrelic/newrelic-capacitor-plugin 
- Added code from here: https://github.com/newrelic/newrelic-capacitor-plugin?tab=readme-ov-file#ionic-capacitor-setup to my Ionic/Angular project's `main.ts` file
- npm build
- npm serve
- ERROR happens preventing the rest of the app from working

## Expected Behavior
Expect the app to run without newrelic errors.  Removed the newrelic pieces, app runs fine.

## Your Environment
Apple M2 Max, Sonoma 14.3
Ionic/Angular app building with Capacitor/Trapeze
Serving to local browser (Chrome)

**Comment by ndesai-newrelic** [comment]
@hughknaus can you run this on mobile phone? can you share sample app for this issue?

**Comment by hughknaus** [comment]
I tried in Android emulator first but the app now crashes with this log:

```
2024-02-12 09:24:31.335 18520-18587 Capacitor               <MYAPP>                 E  Serious error executing plugin
                                                                                                    java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:797)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.IllegalArgumentException: noticeHttpTransaction: URL is malformed: /svg/close.svg
                                                                                                    	at com.newrelic.agent.android.NewRelic.noticeHttpTransaction(NewRelic.java:579)
                                                                                                    	at com.newrelic.capacitor.plugin.NewRelicCapacitorPluginPlugin.noticeHttpTransaction(NewRelicCapacitorPluginPlugin.java:429)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:797) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
2024-02-12 09:24:31.337 18520-18587 AndroidRuntime          <MYAPP>                E  FATAL EXCEPTION: CapacitorPlugins
                                                                                                    Process: <MYAPP>, PID: 18520
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:806)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0)
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138)
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:797)
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
                                                                                                    Caused by: java.lang.IllegalArgumentException: noticeHttpTransaction: URL is malformed: /svg/close.svg
                                                                                                    	at com.newrelic.agent.android.NewRelic.noticeHttpTransaction(NewRelic.java:579)
                                                                                                    	at com.newrelic.capacitor.plugin.NewRelicCapacitorPluginPlugin.noticeHttpTransaction(NewRelicCapacitorPluginPlugin.java:429)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:138) 
                                                                                                    	at com.getcapacitor.Bridge.lambda$callPluginMethod$0(Bridge.java:797) 
                                                                                                    	at com.getcapacitor.Bridge.$r8$lambda$ehFTi5f4HhVNFKTbCKAYDkpQYRA(Unknown Source:0) 
                                                                                                    	at com.getcapacitor.Bridge$$ExternalSyntheticLambda3.run(Unknown Source:8) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67) 
```

I searched the app for `close.svg` and the only reference was inside this file: 
`/Volumes/Storage/_projects/<MYAPP>/android/app/build/intermediates/incremental/mergeDebugAssets/merger.xml`

I couldn't find any information relating to the `merger.xml` file.  I'm assuming that it is an artifact of the Capacitor build??

**Comment by ndesai-newrelic** [comment]
@hughknaus i can fix this issue from our side, did you try to run that on ios device?

**Comment by hughknaus** [comment]
@ndesai-newrelic no, i have not tried on the iOS side yet. Troubleshooting has always been easy in browser, then Android, and finally iOS.  But I'll give it try on the iOS side now, I'll let you know in a little bit what I see.

**Comment by hughknaus** [comment]
@ndesai-newrelic the iOS side definitely doesn't run as expected, but a little harder to tell where the issue lies, here's an XCode screenshot with some Newrelic warnings:
![Uploading Screenshot 2024-02-12 at 2.22.41 PM.png…]()

**Comment by ndesai-newrelic** [comment]
@hughknaus i pushed some changes on our main branch, can you test your app against those changes before release?

**Comment by hughknaus** [comment]
@ndesai-newrelic thanks! I'll give it a try tomorrow, Thursday. I'm in Mountain TZ.

**Comment by Toxiapo** [comment]
Hi @ndesai-newrelic, I am having a similar issue on browser, but works fine on ios and I am wondering if there's a release I can try?  THanks

**Comment by ndesai-newrelic** [comment]
@Toxiapo can you check this release on browser also?

**Comment by Toxiapo** [comment]
@ndesai-newrelic Updated to 1.3.5 and things seem to be working great now! Thank you

**Comment by hughknaus** [comment]
@ndesai-newrelic so 1.3.5 does partially fix the issue.  I can at least load the app in browser now.  I do continue to see the leading empty arrays in the console.log, however, it's no longer on every line but still a majority.  For example:
```
[]: jobFilterService:: []: 2 index.js:22
[]: [object Object] 2 index.js:22
[]: [object Object] index.js:22 
[]: jobFilterService:: []: usw:hknaus@email.com index.js:22 
[]: jobFilterService:: []: usw:hknaus@email.com index.js:22
[]: joblist::ionViewDidEnter fromJobStart = false index.js:22 
```

This is what it normally looks like:
```
jobFilterService:: 7538.28a007c40e5a86a4.js:1 
jobFilterService:: usw:hknaus@accurence.com 7538.28a007c40e5a86a4.js:1 
jobFilterService:: usw:hknaus@accurence.com
joblist::ionViewDidEnter fromJobStart = false 6377.dd8d15ed994e8c44.js:1
```

I'm continuing to test Android and iOS today.

**Comment by ndesai-newrelic** [comment]
@hughknaus That's an astute observation. We are currently automatically collecting logs which may be adding these empty arrays. Could you please open a new issue for this?
